CREATE TABLE IF NOT EXISTS "tasks" (
  "task_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "title" text NOT NULL,
  "status" varchar(32) NOT NULL DEFAULT 'Not start',
  "description" text,
  "created_at" timestamptz DEFAULT now(),
  "updated_at" timestamptz DEFAULT now(),
  "deleted_at" timestamptz
);

CREATE TABLE IF NOT EXISTS "users" (
  "user_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fullname" varchar NOT NULL,
  "username" varchar UNIQUE NOT NULL,
  "password" varchar NOT NULL,
  "created_at" timestamptz DEFAULT now(), 
  "updated_at" timestamptz DEFAULT now(),
  "deleted_at" timestamptz
);

ALTER TABLE IF EXISTS "tasks" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");