// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	auth_entity "github.com/huynhtruongson/simple-todo/services/auth/entity"

	context "context"

	mock "github.com/stretchr/testify/mock"
)

// AuthService is an autogenerated mock type for the AuthService type
type AuthService struct {
	mock.Mock
}

type AuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthService) EXPECT() *AuthService_Expecter {
	return &AuthService_Expecter{mock: &_m.Mock}
}

// Login provides a mock function with given fields: ctx, credential, loginInfo
func (_m *AuthService) Login(ctx context.Context, credential auth_entity.Credential, loginInfo auth_entity.LoginInfo) (string, string, error) {
	ret := _m.Called(ctx, credential, loginInfo)

	var r0 string
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, auth_entity.Credential, auth_entity.LoginInfo) (string, string, error)); ok {
		return rf(ctx, credential, loginInfo)
	}
	if rf, ok := ret.Get(0).(func(context.Context, auth_entity.Credential, auth_entity.LoginInfo) string); ok {
		r0 = rf(ctx, credential, loginInfo)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, auth_entity.Credential, auth_entity.LoginInfo) string); ok {
		r1 = rf(ctx, credential, loginInfo)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, auth_entity.Credential, auth_entity.LoginInfo) error); ok {
		r2 = rf(ctx, credential, loginInfo)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// AuthService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type AuthService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - credential auth_entity.Credential
//   - loginInfo auth_entity.LoginInfo
func (_e *AuthService_Expecter) Login(ctx interface{}, credential interface{}, loginInfo interface{}) *AuthService_Login_Call {
	return &AuthService_Login_Call{Call: _e.mock.On("Login", ctx, credential, loginInfo)}
}

func (_c *AuthService_Login_Call) Run(run func(ctx context.Context, credential auth_entity.Credential, loginInfo auth_entity.LoginInfo)) *AuthService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(auth_entity.Credential), args[2].(auth_entity.LoginInfo))
	})
	return _c
}

func (_c *AuthService_Login_Call) Return(acToken string, rfToken string, e error) *AuthService_Login_Call {
	_c.Call.Return(acToken, rfToken, e)
	return _c
}

func (_c *AuthService_Login_Call) RunAndReturn(run func(context.Context, auth_entity.Credential, auth_entity.LoginInfo) (string, string, error)) *AuthService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// RenewToken provides a mock function with given fields: ctx, rfToken
func (_m *AuthService) RenewToken(ctx context.Context, rfToken string) (string, error) {
	ret := _m.Called(ctx, rfToken)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, rfToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, rfToken)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, rfToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthService_RenewToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenewToken'
type AuthService_RenewToken_Call struct {
	*mock.Call
}

// RenewToken is a helper method to define mock.On call
//   - ctx context.Context
//   - rfToken string
func (_e *AuthService_Expecter) RenewToken(ctx interface{}, rfToken interface{}) *AuthService_RenewToken_Call {
	return &AuthService_RenewToken_Call{Call: _e.mock.On("RenewToken", ctx, rfToken)}
}

func (_c *AuthService_RenewToken_Call) Run(run func(ctx context.Context, rfToken string)) *AuthService_RenewToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *AuthService_RenewToken_Call) Return(_a0 string, _a1 error) *AuthService_RenewToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthService_RenewToken_Call) RunAndReturn(run func(context.Context, string) (string, error)) *AuthService_RenewToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewAuthService creates a new instance of AuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthService {
	mock := &AuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
