// Code generated by "stringer -type TaskStatus -trimprefix TaskStatus"; DO NOT EDIT.

package task_entity

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TaskStatusNotStart-0]
	_ = x[TaskStatusDoing-1]
	_ = x[TaskStatusFinish-2]
}

const _TaskStatus_name = "NotStartDoingFinish"

var _TaskStatus_index = [...]uint8{0, 8, 13, 19}

func (i TaskStatus) String() string {
	if i < 0 || i >= TaskStatus(len(_TaskStatus_index)-1) {
		return "TaskStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TaskStatus_name[_TaskStatus_index[i]:_TaskStatus_index[i+1]]
}
